services:
- type: web
  name: gitpod-openvscode-server-example
  env: docker
  repo: https://github.com/AG123-321/quizizz-server.git
  autoDeploy: false
  disk:
    name: data
    mountPath: /home/workspace
    sizeGB: 1
